smallbankArgs: &smallbank-args
  accountsGenerated: 10000
  txnPerBatch: 1

test:
  name: smallbank-world-state-query
  description: Query Smallbank world state and save to JSON file.
  workers:
    number: 1
  rounds:
    - label: query-world-state
      txNumber: 1
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/smallbank/queryWorldState.js
        arguments:
          <<: *smallbank-args
          contractId: smallbank
          outputPath: /root/ruc/data/benchmark/world_state.json
